[package]
authors = ["Ballerina"]
distribution = "2201.12.3"
export = ["health.hl7v2.utils.v2tofhirr4"]
keywords = ["Healthcare", "HL7", "V2", "FHIR", "Name/HL7 V2 to FHIR R4", "Vendor/Other", "Area/Healthcare", "Type/Library"]
icon = "icon.png"
readme = "README.md"
name = "health.hl7v2.utils.v2tofhirr4"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"
version = "4.0.6"

#[build-options]
#optimizeDependencyCompilation = true
