[package]
org = "ballerinax"
name = "health.hl7v24"
version = "4.0.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "HL7", "HL7v2.4"]
distribution = "2201.12.2"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"
