[package]
org = "ballerinax"
name = "health.hl7v271"
version = "1.0.1"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.7.1"]
distribution = "2201.5.0"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.4"
