[package]
org = "ballerinax"
name = "health.hl7v271"
version = "3.0.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "HL7", "HL7v2.7.1"]
distribution = "2201.8.1"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "2.2.0"
