name: daily-build-hl7v271

on:
  schedule:
    - cron: '50 20 * * *'    # 02:20 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: hl7v271
      