name: daily-build-hl7v251

on:
  schedule:
    - cron: '45 20 * * *'    # 02:15 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: hl7v251
      